projectType: runtime
mavenTool: "3.9.5"
additionalTestConfigs:
  default:
    testJdkTool: TEMURIN-JDK8
    mavenAdditionalArgs: -DruntimeVersion=4.3.0 -DruntimeProduct=MULE_EE
  jdk8-4.4.x:
    testJdkTool: TEMURIN-JDK8
    mavenAdditionalArgs: -DruntimeVersion=4.4.0 -DruntimeProduct=MULE_EE
  jdk8-4.5.x:
    testJdkTool: TEMURIN-JDK8
    mavenAdditionalArgs: -DruntimeVersion=4.5.4 -DruntimeProduct=MULE_EE
  jdk8-4.6.x:
    testJdkTool: TEMURIN-JDK8
    mavenAdditionalArgs: -DruntimeVersion=4.6.19 -DruntimeProduct=MULE_EE
  jdk8-4.7.x:
    testJdkTool: TEMURIN-JDK8
    mavenAdditionalArgs: -DruntimeVersion=4.7.4 -DruntimeProduct=MULE_EE
  jdk8-4.8.x:
    testJdkTool: TEMURIN-JDK8
    mavenAdditionalArgs: -DruntimeVersion=4.8.6 -DruntimeProduct=MULE_EE


  jdk11-4.3.x:
    testJdkTool: TEMURIN-JDK11
    mavenAdditionalArgs: -DruntimeVersion=4.3.0 -DruntimeProduct=MULE_EE
  jdk11-4.4.x:
    testJdkTool: TEMURIN-JDK11
    mavenAdditionalArgs: -DruntimeVersion=4.4.0 -DruntimeProduct=MULE_EE
  jdk11-4.5.x:
    testJdkTool: TEMURIN-JDK11
    mavenAdditionalArgs: -DruntimeVersion=4.5.4 -DruntimeProduct=MULE_EE
  jdk11-4.6.x:
    testJdkTool: TEMURIN-JDK11
    mavenAdditionalArgs: -DruntimeVersion=4.6.19 -DruntimeProduct=MULE_EE
  jdk11-4.7.x:
    testJdkTool: TEMURIN-JDK11
    mavenAdditionalArgs: -DruntimeVersion=4.7.4 -DruntimeProduct=MULE_EE
  jdk11-4.8.x:
    testJdkTool: TEMURIN-JDK11
    mavenAdditionalArgs: -DruntimeVersion=4.8.6 -DruntimeProduct=MULE_EE

  jdk17:
    testJdkTool: TEMURIN-JDK17
    mavenAdditionalArgs: -Pdocker -Pjava-17-plus -DfailIfNoTests=false -DminVersion=4.6.0
