projectType: runtime
mavenTool: "3.9.5"
additionalTestConfigs:
  # For Java 8, munits are failing for runtime < 4.3.0 after updating munit.extensions.maven.plugin.version to above 1.3.0
  default:
    mavenAdditionalArgs: -DfailIfNoTests=false -DruntimeVersion=4.3.0 -DadditionalRuntimeVersions=4.4.0 -DruntimeProduct=MULE_EE
  jdk11:
    testJdkTool: TEMURIN-JDK11
    mavenAdditionalArgs: -DfailIfNoTests=false -DruntimeVersion="4.5.4" -DadditionalRuntimeVersions=4.6.19 -DadditionalRuntimeVersions=4.8.6 -DruntimeProduct=MULE_EE
  jdk17:
    testJdkTool: TEMURIN-JDK17
    mavenAdditionalArgs: -DfailIfNoTests=false -DruntimeVersion=4.9.6 -DruntimeProduct=MULE_EE
